require:
  - rubocop-performance
  - rubocop-rspec
  - rubocop-rails

Layout/LineLength:
  Max: 85

Style/StringLiterals:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/HashEachMethods:
  Enabled: false

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Naming/VariableNumber:
  Enabled: false

Metrics/MethodLength:
  Max: 20

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

Layout/HeredocIndentation:
  Exclude:
    - "**/*_spec.rb"

RSpec/NamedSubject:
  Enabled: false

RSpec/ContextWording:
  Enabled: false

RSpec/MessageSpies:
  EnforcedStyle: 'receive'

AllCops:
  TargetRubyVersion: 2.4
  DisplayCopNames: true
  Exclude:
    - 'config.ru'
    - 'Rakefile'
    - 'node_modules/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'bin/**/*'
    - 'lib/tasks/**/*'
    - 'spec/support/**/*'
    - '**/*.erb'
